version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Installing Packages
          command: yarn --ignore-engines install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running Prettier
          command: yarn run lint-staged

      - run:
          name: Running Linter
          command: yarn run lint

      - run:
          name: Running Flow
          command: yarn run flow

      - run:
          name: Running Tests
          command: yarn run test
